#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : neutron
Version  : 7.0.2
Release  : 46
URL      : http://tarballs.openstack.org/neutron/neutron-7.0.2.tar.gz
Source0  : http://tarballs.openstack.org/neutron/neutron-7.0.2.tar.gz
Source1  : neutron-dhcp-agent.service
Source2  : neutron-l3-agent.service
Source3  : neutron-linuxbridge-agent.service
Source4  : neutron-metadata-agent.service
Source5  : neutron-openvswitch-agent.service
Source6  : neutron-server.service
Source7  : neutron.tmpfiles
Summary  : OpenStack Networking
Group    : Development/Tools
License  : Apache-2.0
Requires: neutron-bin
Requires: neutron-python
Requires: neutron-config
Requires: neutron-data
BuildRequires : Babel-python
BuildRequires : Jinja2
BuildRequires : Mako-python
BuildRequires : Paste-python
BuildRequires : PasteDeploy-python
BuildRequires : PyYAML-python
BuildRequires : Pygments
BuildRequires : Routes-python
BuildRequires : SQLAlchemy-python
BuildRequires : Sphinx-python
BuildRequires : Tempita-python
BuildRequires : WebOb-python
BuildRequires : WebTest
BuildRequires : aioeventlet-python
BuildRequires : alembic-python
BuildRequires : amqp-python
BuildRequires : anyjson-python
BuildRequires : beautifulsoup4-python
BuildRequires : cliff-python
BuildRequires : cmd2-python
BuildRequires : coverage-python
BuildRequires : decorator-python
BuildRequires : discover-python
BuildRequires : docutils-python
BuildRequires : eventlet-python
BuildRequires : extras
BuildRequires : fixtures-python
BuildRequires : flake8-python
BuildRequires : funcsigs
BuildRequires : futures-python
BuildRequires : greenlet-python
BuildRequires : hacking
BuildRequires : httplib2
BuildRequires : iso8601-python
BuildRequires : jsonrpclib-python
BuildRequires : jsonschema-python
BuildRequires : keystonemiddleware
BuildRequires : kombu-python
BuildRequires : linecache2-python
BuildRequires : markupsafe-python
BuildRequires : mccabe-python
BuildRequires : mox3-python
BuildRequires : msgpack-python-python
BuildRequires : netaddr-python
BuildRequires : netifaces-python
BuildRequires : oslo.concurrency-python
BuildRequires : oslo.config
BuildRequires : oslo.context-python
BuildRequires : oslo.db-python
BuildRequires : oslo.i18n-python
BuildRequires : oslo.log-python
BuildRequires : oslo.messaging-python
BuildRequires : oslo.middleware-python
BuildRequires : oslo.policy
BuildRequires : oslo.rootwrap-python
BuildRequires : oslo.serialization-python
BuildRequires : oslo.utils-python
BuildRequires : oslo.versionedobjects
BuildRequires : oslosphinx-python
BuildRequires : oslotest-python
BuildRequires : pbr
BuildRequires : pep8
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : posix_ipc-python
BuildRequires : prettytable
BuildRequires : py-python
BuildRequires : pycadf-python
BuildRequires : pyflakes-python
BuildRequires : pyparsing-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python-keystoneclient-python
BuildRequires : python-mimeparse-python
BuildRequires : python-mock
BuildRequires : python-neutronclient-python
BuildRequires : python-novaclient-python
BuildRequires : python-subunit
BuildRequires : pytz-python
BuildRequires : repoze.lru-python
BuildRequires : requests-mock-python
BuildRequires : requests-python
BuildRequires : retrying-python
BuildRequires : setuptools
BuildRequires : simplejson
BuildRequires : six
BuildRequires : six-python
BuildRequires : sqlalchemy-migrate-python
BuildRequires : sqlparse
BuildRequires : stevedore-python
BuildRequires : tempest-lib-python
BuildRequires : testrepository-python
BuildRequires : testresources
BuildRequires : testscenarios
BuildRequires : testtools
BuildRequires : testtools-python
BuildRequires : tox
BuildRequires : traceback2-python
BuildRequires : trollius-python
BuildRequires : unittest2-python
BuildRequires : virtualenv
BuildRequires : waitress-python
Patch1: 0001-neutron-sudoers-entry.patch
Patch2: 0002-move-rootwrap-location.patch
Patch3: 0003-default-config.patch
Patch4: 0004-change-dnsmasq-location.patch

%description
This package contains files that are required for XenAPI support for Neutron.

%package bin
Summary: bin components for the neutron package.
Group: Binaries
Requires: neutron-data
Requires: neutron-config

%description bin
bin components for the neutron package.


%package config
Summary: config components for the neutron package.
Group: Default

%description config
config components for the neutron package.


%package data
Summary: data components for the neutron package.
Group: Data

%description data
data components for the neutron package.


%package python
Summary: python components for the neutron package.
Group: Default
Requires: Jinja2
Requires: Paste-python
Requires: PasteDeploy-python
Requires: Routes-python
Requires: SQLAlchemy-python
Requires: WebOb-python
Requires: alembic-python
Requires: eventlet-python
Requires: greenlet-python
Requires: httplib2
Requires: keystonemiddleware
Requires: oslo.concurrency-python
Requires: oslo.config
Requires: oslo.context-python
Requires: oslo.db-python
Requires: oslo.i18n-python
Requires: oslo.log-python
Requires: oslo.messaging-python
Requires: oslo.middleware-python
Requires: oslo.rootwrap-python
Requires: oslo.serialization-python
Requires: oslo.utils-python
Requires: python-keystoneclient-python
Requires: python-neutronclient-python
Requires: python-novaclient-python
Requires: requests-python
Requires: retrying-python
Requires: six-python

%description python
python components for the neutron package.


%prep
%setup -q -n neutron-7.0.2
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1

%build
python2 setup.py build -b py2

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python2.7/site-packages python2 setup.py test
%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/neutron-dhcp-agent.service
install -m 0644 %{SOURCE2} %{buildroot}/usr/lib/systemd/system/neutron-l3-agent.service
install -m 0644 %{SOURCE3} %{buildroot}/usr/lib/systemd/system/neutron-linuxbridge-agent.service
install -m 0644 %{SOURCE4} %{buildroot}/usr/lib/systemd/system/neutron-metadata-agent.service
install -m 0644 %{SOURCE5} %{buildroot}/usr/lib/systemd/system/neutron-openvswitch-agent.service
install -m 0644 %{SOURCE6} %{buildroot}/usr/lib/systemd/system/neutron-server.service
mkdir -p %{buildroot}/usr/lib/tmpfiles.d
install -m 0644 %{SOURCE7} %{buildroot}/usr/lib/tmpfiles.d/neutron.conf
## make_install_append content
rm -rf %{buildroot}/usr/etc
install -d -m 755 %{buildroot}/usr/share/defaults/neutron
install -d -m 755 %{buildroot}/usr/share/defaults/neutron/conf.d
install -p -D -m 644 etc/*.conf %{buildroot}/usr/share/defaults/neutron/
install -p -D -m 644 etc/*.ini %{buildroot}/usr/share/defaults/neutron/
install -p -D -m 644 etc/*.json %{buildroot}/usr/share/defaults/neutron/
install -d -m 755 %{buildroot}/usr/share/neutron/rootwrap.d
mv %{buildroot}/usr/share/defaults/neutron/rootwrap.conf %{buildroot}/usr/share/neutron/
install -p -D -m 640 etc/neutron/rootwrap.d/*.filters %{buildroot}/usr/share/neutron/rootwrap.d/
install -d -m 755 %{buildroot}/usr/share/neutron/plugins
mv etc/neutron/plugins/* %{buildroot}/usr/share/neutron/plugins/
install -d -m 750 %{buildroot}/usr/share/defaults/sudo/sudoers.d
install -p -D -m 440 neutron.sudoers %{buildroot}/usr/share/defaults/sudo/sudoers.d/neutron
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/neutron-db-manage
/usr/bin/neutron-debug
/usr/bin/neutron-dev-server
/usr/bin/neutron-dhcp-agent
/usr/bin/neutron-hyperv-agent
/usr/bin/neutron-ipset-cleanup
/usr/bin/neutron-keepalived-state-change
/usr/bin/neutron-l3-agent
/usr/bin/neutron-linuxbridge-agent
/usr/bin/neutron-metadata-agent
/usr/bin/neutron-metering-agent
/usr/bin/neutron-mlnx-agent
/usr/bin/neutron-netns-cleanup
/usr/bin/neutron-ns-metadata-proxy
/usr/bin/neutron-nvsd-agent
/usr/bin/neutron-openvswitch-agent
/usr/bin/neutron-ovs-cleanup
/usr/bin/neutron-ovsvapp-agent
/usr/bin/neutron-pd-notify
/usr/bin/neutron-restproxy-agent
/usr/bin/neutron-rootwrap
/usr/bin/neutron-rootwrap-daemon
/usr/bin/neutron-rootwrap-xen-dom0
/usr/bin/neutron-rpc-server
/usr/bin/neutron-sanity-check
/usr/bin/neutron-server
/usr/bin/neutron-sriov-nic-agent
/usr/bin/neutron-usage-audit

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/neutron-dhcp-agent.service
/usr/lib/systemd/system/neutron-l3-agent.service
/usr/lib/systemd/system/neutron-linuxbridge-agent.service
/usr/lib/systemd/system/neutron-metadata-agent.service
/usr/lib/systemd/system/neutron-openvswitch-agent.service
/usr/lib/systemd/system/neutron-server.service
/usr/lib/tmpfiles.d/neutron.conf

%files data
%defattr(-,root,root,-)
/usr/share/defaults/neutron/api-paste.ini
/usr/share/defaults/neutron/dhcp_agent.ini
/usr/share/defaults/neutron/l3_agent.ini
/usr/share/defaults/neutron/metadata_agent.ini
/usr/share/defaults/neutron/metering_agent.ini
/usr/share/defaults/neutron/neutron.conf
/usr/share/defaults/neutron/policy.json
/usr/share/defaults/sudo/sudoers.d/neutron
/usr/share/neutron/plugins/bigswitch/restproxy.ini
/usr/share/neutron/plugins/bigswitch/ssl/ca_certs/README
/usr/share/neutron/plugins/bigswitch/ssl/host_certs/README
/usr/share/neutron/plugins/brocade/brocade.ini
/usr/share/neutron/plugins/brocade/brocade_mlx.ini
/usr/share/neutron/plugins/brocade/vyatta/vrouter.ini
/usr/share/neutron/plugins/cisco/cisco_vpn_agent.ini
/usr/share/neutron/plugins/embrane/heleos_conf.ini
/usr/share/neutron/plugins/midonet/midonet.ini
/usr/share/neutron/plugins/ml2/linuxbridge_agent.ini
/usr/share/neutron/plugins/ml2/ml2_conf.ini
/usr/share/neutron/plugins/ml2/ml2_conf_brocade.ini
/usr/share/neutron/plugins/ml2/ml2_conf_brocade_fi_ni.ini
/usr/share/neutron/plugins/ml2/ml2_conf_fslsdn.ini
/usr/share/neutron/plugins/ml2/ml2_conf_ofa.ini
/usr/share/neutron/plugins/ml2/ml2_conf_sriov.ini
/usr/share/neutron/plugins/ml2/openvswitch_agent.ini
/usr/share/neutron/plugins/ml2/sriov_agent.ini
/usr/share/neutron/plugins/mlnx/mlnx_conf.ini
/usr/share/neutron/plugins/nuage/nuage_plugin.ini
/usr/share/neutron/plugins/oneconvergence/nvsdplugin.ini
/usr/share/neutron/plugins/opencontrail/contrailplugin.ini
/usr/share/neutron/plugins/ovsvapp/ovsvapp_agent.ini
/usr/share/neutron/rootwrap.conf
/usr/share/neutron/rootwrap.d/debug.filters
/usr/share/neutron/rootwrap.d/dhcp.filters
/usr/share/neutron/rootwrap.d/dibbler.filters
/usr/share/neutron/rootwrap.d/ebtables.filters
/usr/share/neutron/rootwrap.d/ipset-firewall.filters
/usr/share/neutron/rootwrap.d/iptables-firewall.filters
/usr/share/neutron/rootwrap.d/l3.filters
/usr/share/neutron/rootwrap.d/linuxbridge-plugin.filters
/usr/share/neutron/rootwrap.d/openvswitch-plugin.filters

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
